name: Build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo install --path helix-term --locked
    - uses: actions/upload-artifact@v4
      with:
        name: helix
        path: C:\Users\runneradmin\.cargo\bin\hx.exe
